---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      ColorVariable:
        enabled: false
      SingleLinePerSelector:
        enabled: false
      HexNotation:
        enabled: false
      HexLength:
        enabled: false
      LeadingZero:
        enabled: false
      SelectorFormat:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - src/**
  - Gemfile.lock
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- build/**/*
- documentation/**/*
- _site/**/*
- src/css/util/modular-scale/*
