# Markdown config
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

name: KPCC style guide

source: documentation

version: 0.3.0

exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- ".sass-cache"
- ".ruby-version"
- src/css/base
- src/css/components
- src/css/layout
- src/css/main.scss
- src/img
- src/js

permalink: pretty

repos:
- name: SCPR Style Guide
  description: Product Style Guide for KPCC (Southern California Public Radio).
  url: https://github.com/SCPR/scpr-style-guide

sass:
  load_paths:
    - documentation/_sass
    - src/css/util
#  style: :compressed

collections:
  components:
    output: true
    permalink: /:path/
